### PR TITLE
chore: Allow Laravel 10 & PHP 8.2

### PR DESCRIPTION
**Pull request by chris-ware**

### CODE REVIEW

**Comment by alexsoft** [comment]
Tests have to run on 8.2 as well

**Comment by chris-ware** [comment]
@alexsoft I've checked and I think I've correctly updated the necessary locations for test to occur on PHP 8.2

**Comment by alexsoft** [comment]
@chris-ware can you please drop verbose option from phpunit command, as it causes issues on PHPUnit ^10. It is not very much needed, thus can be dropped

**Comment by alexsoft** [comment]
Thank you for modifications

**Pull request merged**
